In [1]:
import numpy as np

In [2]:
np.array([1,2,3])

array([1, 2, 3])

In [3]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
np.array([[[1,2,3],[4,5,6],[7,8,9]]])

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [9]:
np.array([[[1,2,3],[4,5,6],[7,8,9]]])

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [8]:
a.ndim

3

In [10]:
m = np.matrix([1,2,3,4])

In [11]:
m

matrix([[1, 2, 3, 4]])

In [13]:
np.fromfunction(lambda i,j : i==j, (3,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False]])

In [14]:
np.random.rand(2,3)

array([[0.10334844, 0.02011598, 0.96519119],
       [0.5632308 , 0.8992148 , 0.7923848 ]])

In [15]:
np.random.rand(1,4,4)

array([[[0.3029297 , 0.38782671, 0.87653668, 0.80499464],
        [0.26006837, 0.9832911 , 0.50228784, 0.69417931],
        [0.61636295, 0.04739174, 0.64986696, 0.47601565],
        [0.81335951, 0.29802509, 0.61169348, 0.04672797]]])

In [16]:
np.random.randn(1,4,4)

array([[[ 0.18858504,  1.73068866,  0.40987896, -0.6149568 ],
        [-0.84702102, -1.70040312, -0.73950962, -1.36677319],
        [-0.51167596, -0.50542734, -1.88953189,  0.23789695],
        [-0.14618294,  0.17162761, -0.17487776,  0.89063636]]])

In [17]:
np.random.randn(20,5,5)

array([[[-2.04394494e+00,  5.74547549e-01, -3.08769811e-01,
         -2.68576990e-01,  1.48754731e+00],
        [-1.80950720e-01,  9.34089944e-01, -8.28181233e-01,
         -1.34945356e+00,  6.55891557e-01],
        [ 1.10962089e+00, -1.51381518e+00,  1.18259649e+00,
         -2.03222997e-01,  6.09119739e-01],
        [-1.68637156e+00,  1.15720336e+00,  1.24096086e+00,
          5.74796374e-01,  2.92095442e+00],
        [-1.04114471e+00,  6.22589790e-01, -8.40524507e-01,
         -4.30935515e-01, -2.86822745e-01]],

       [[-1.31631020e+00,  1.28739157e+00,  7.46548897e-02,
         -4.74948889e-01, -1.36733028e-01],
        [ 1.36238331e+00, -3.26527099e-02,  6.16271387e-01,
          1.13639797e+00, -2.07751296e-01],
        [-3.38328609e-01,  9.25684779e-01, -9.74785145e-01,
          1.15272570e+00, -1.12054559e+00],
        [ 7.62230115e-01, -1.58126154e+00, -8.15126076e-01,
         -1.14547545e+00,  1.65524326e+00],
        [ 1.19497215e+00,  1.26655761e+00, -3.44140435e-01,
  

In [24]:
d =np.random.randint(0,10,(4,4))

In [27]:
import pandas as pd

In [28]:
pd.DataFrame(d)

0  1  2  3
0  5  5  3  9
1  3  1  8  0
2  5  5  4  8
3  1  5  6  7

In [30]:
d.reshape(8,2)

array([[5, 5],
       [3, 9],
       [3, 1],
       [8, 0],
       [5, 5],
       [4, 8],
       [1, 5],
       [6, 7]])