In [1]:
import numpy as np

In [2]:
range(0,10)

range(0, 10)

In [3]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
np.arange(0.5,10)

array([0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5, 9.5])

In [5]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(5,-4,-.5)

array([ 5. ,  4.5,  4. ,  3.5,  3. ,  2.5,  2. ,  1.5,  1. ,  0.5,  0. ,
       -0.5, -1. , -1.5, -2. , -2.5, -3. , -3.5])

In [7]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [8]:
np.logspace(1,50,10)

array([1.00000000e+01, 2.78255940e+06, 7.74263683e+11, 2.15443469e+17,
       5.99484250e+22, 1.66810054e+28, 4.64158883e+33, 1.29154967e+39,
       3.59381366e+44, 1.00000000e+50])

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros((3,5,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [16]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
a =np.eye(3)

In [20]:
a.shape

(3, 3)

In [21]:
a.ndim

2

In [22]:

a.size

9

In [23]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
print ("i love srilakshmi")

i love srilakshmi


In [25]:
b =np.random.randn(3,4)

In [26]:
b

array([[ 1.5112722 , -0.37642104,  1.61240211,  0.12658269],
       [ 0.43945756, -0.22967464, -0.51545447, -0.34309994],
       [-0.94256927, -0.94459543,  0.47620132,  0.53313838]])

In [28]:
b[1][1]

-0.22967464446631403

In [40]:
b[[0,1],0:2]

array([[ 1.5112722 , -0.37642104],
       [ 0.43945756, -0.22967464]])

In [41]:
b[0:2,0:2]

array([[ 1.5112722 , -0.37642104],
       [ 0.43945756, -0.22967464]])

In [51]:
m1 = np.random.randint(1,3,(3,3))

In [52]:
m1

array([[1, 1, 1],
       [1, 1, 2],
       [2, 2, 2]])

In [53]:
m2 = np.random.randint(2,4,(3,3))

In [54]:
m2

array([[3, 2, 3],
       [2, 3, 3],
       [3, 3, 3]])

In [56]:
m1@m2  #matrix multiplication 

array([[ 8,  8,  9],
       [11, 11, 12],
       [16, 16, 18]])